[{"name": "test.test_summary.Summary.test_calls", "status": "errored", "message": "[Errno 22] Invalid argument: 'test\\test_summary.py'", "passed": false, "points": ["p02-05.1"], "backtrace": ["  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\test\\test_summary.py\", line 49, in test_calls\n    summary(\"src/example.txt\")\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\src\\summary.py\", line 11, in summary\n    with open(filename, 'r') as f:\n         ^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\mock.py\", line 1118, in __call__\n    return self._mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\mock.py\", line 1122, in _mock_call\n    return self._execute_mock_call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\mock.py\", line 1183, in _execute_mock_call\n    result = effect(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^\n"]}, {"name": "test.test_summary.Summary.test_main", "status": "passed", "message": "", "passed": true, "points": ["p02-05.1"], "backtrace": []}, {"name": "test.test_summary.Summary.test_missing_file", "status": "errored", "message": "[Errno 22] Invalid argument: 'test\\test_summary.py'", "passed": false, "points": ["p02-05.1"], "backtrace": ["  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\test\\test_summary.py\", line 44, in test_missing_file\n    summary(\"doesnotexist\")\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\src\\summary.py\", line 11, in summary\n    with open(filename, 'r') as f:\n         ^^^^^^^^^^^^^^^^^^^\n"]}, {"name": "test.test_summary.Summary.test_one", "status": "errored", "message": "[Errno 22] Invalid argument: 'test\\test_summary.py'", "passed": false, "points": ["p02-05.1"], "backtrace": ["  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\test\\test_summary.py\", line 22, in test_one\n    s,a,d = summary(\"src/example.txt\")\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\src\\summary.py\", line 11, in summary\n    with open(filename, 'r') as f:\n         ^^^^^^^^^^^^^^^^^^^\n"]}, {"name": "test.test_summary.Summary.test_three", "status": "errored", "message": "[Errno 22] Invalid argument: 'test\\test_summary.py'", "passed": false, "points": ["p02-05.2"], "backtrace": ["  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\test\\test_summary.py\", line 36, in test_three\n    s,a,d = summary(\"src/example3.txt\")\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\src\\summary.py\", line 11, in summary\n    with open(filename, 'r') as f:\n         ^^^^^^^^^^^^^^^^^^^\n"]}, {"name": "test.test_summary.Summary.test_two", "status": "errored", "message": "[Errno 22] Invalid argument: 'test\\test_summary.py'", "passed": false, "points": ["p02-05.1"], "backtrace": ["  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 57, in testPartExecutor\n    yield\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 623, in run\n    self._callTestMethod(testMethod)\n", "  File \"C:\\Program Files\\Python311\\Lib\\unittest\\case.py\", line 579, in _callTestMethod\n    if method() is not None:\n       ^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\test\\test_summary.py\", line 29, in test_two\n    s,a,d = summary(\"src/example2.txt\")\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Program Files\\Python Project\\P1\\PythonData-1\\øvelser\\e25_summary\\src\\summary.py\", line 11, in summary\n    with open(filename, 'r') as f:\n         ^^^^^^^^^^^^^^^^^^^\n"]}]